language: C
before_install:
    - sudo apt-get update
install:
    - sudo apt-get install -y autoconf texinfo
    - git clone https://github.com/libcheck/check
    - cd check
    - autoreconf --install
    - ./configure
    - make
    - sudo make install
    - sudo ldconfig
before_script:
    - cd $TRAVIS_BUILD_DIR
script: autoreconf --install && ./configure && make && make check
